package at.oekosol.usermanagementservice.mapper;

import at.oekosol.usermanagementservice.dtos.CompanyCreateDTO;
import at.oekosol.usermanagementservice.model.Company;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

@Mapper(componentModel = "spring")
public interface CompanyCreateMapper {
    CompanyCreateMapper INSTANCE = Mappers.getMapper(CompanyCreateMapper.class);

    @Mapping(target = "organizationId", ignore = true)  // Ignore ID as it is autogenerated
    @Mapping(target = "users", ignore = true)  // Ignore users as it is transient
    Company toEntity(CompanyCreateDTO companyCreateDTO);
}
